apiVersion: apps/v1
kind: Deployment
metadata:
  name: eat-api
  labels:
    app: eat-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eat-api
  template:
    metadata:
      labels:
        app: eat-api
    spec:
      imagePullSecrets:
        - name:  docker-sirpi
      containers:
      - name: eat-api
        image: sirpi/sirpi-eat:1.0.0-api-dev
        resources:
          requests:
            memory: "128Mi"
            cpu: "512m"
          limits:
            memory: "128Mi"
            cpu: "512m"
        ports:
        - containerPort: 5000
          name: liveness-port

        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 10

        startupProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: eat-api
spec:
  selector:
    app: eat-api
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
